export const staticProductsFallback = [
  // Lollipops & Gums (Category/Lollipops and Bubblegum)
  { id: 101, name: "BABA LOVELY POP BLUEBERRY", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/BABA LOVELY POP BLUEBERRY MARKUP.png" },
  { id: 102, name: "BABA LOVELY POP GUAVA", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/BABA LOVELY POP GUAVA MARKUP.png" },
  { id: 103, name: "BABA LOVELY POP MANGO", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/BABA LOVELY POP MANGO MARKUP.png" },
  { id: 104, name: "BABA LOVELY POP ORANGE", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/BABA LOVELY POP ORANGE MARKUP.png" },
  { id: 105, name: "BABA LOVELY POP STRAWBERRY ICECREAM", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/BABA LOVELY POP STRAWBERRY ICECREAM MARKUP.png" },
  { id: 106, name: "BABA LOVELY POP STRAWBERRY", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/BABA LOVELY POP STRAWBERRY MARKUP.png" },
  { id: 107, name: "BABA LOVELY POP WATERMELON", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/BABA LOVELY POP WATERMELON MARKUP.png" },
  { id: 108, name: "DJ Bigg Boom", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/DJ Bigg Boom Markup.png" },
  { id: 109, name: "DJ Butter pop", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/DJ Butter pop markup.png" },
  { id: 110, name: "DJ Color Pop", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/DJ Color Pop Markup.png" },
  { id: 111, name: "DJ Fruitoo lollipops", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/DJ Fruitoo lollipops markup.png" },
  { id: 112, name: "DJ Gum Pops", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/DJ Gum Pops Markup.png" },
  { id: 113, name: "DJ Love Pop", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/DJ Love Pop Markup.png" },
  { id: 114, name: "DJ Milk Pop", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/DJ Milk Pop Markup.png" },
  { id: 115, name: "DJ OLIVARY Bubblegum", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/DJ OLIVARY Bubblegum Markup.png" },
  { id: 116, name: "DJ Whistle Lollipops", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/DJ Whistle Lollipops Markup.png" },
  { id: 117, name: "DJ Yogurt Pop Lollipop", category: "Lollipops", image: "/Category/Lollipops and Bubblegum/DJ Yogurt Pop Lollipop Markup.png" },

  // Candies & Toffees (Category/Candies and toffees)
  { id: 201, name: "DJ Butter and Milk Candy", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Butter and Milk Candy.png" },
  { id: 202, name: "DJ Choco Eclairs Jar", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Choco Eclairs Jar Markup.png" },
  { id: 203, name: "DJ Choco Eclairs Pouch", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Choco Eclairs Markup Pouch.png" },
  { id: 204, name: "DJ Chocofull Toffee", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Chocofull Toffee Markup.png" },
  { id: 205, name: "DJ Chocolate Jar", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Chocolate Jar Markup.png" },
  { id: 206, name: "DJ Coconut Desire Toffee", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Coconut Desire Toffee Markup.png" },
  { id: 207, name: "DJ Coconut Eclairs Jar", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Coconut Eclairs Jar Markup.png" },
  { id: 208, name: "DJ Frubon Jar", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Frubon Jar Markup.png" },
  { id: 209, name: "DJ Frubon Pouch", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Frubon Pouch Markup.png" },
  { id: 210, name: "DJ Fruit Shots Toffee", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Fruit Shots Toffee Markup.png" },
  { id: 211, name: "DJ Fruits Candy", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Fruits Candy Markup.png" },
  { id: 212, name: "DJ LOL Candy", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ LOL Candy Markup.png" },
  { id: 213, name: "DJ Milk Candy", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Milk Candy Markup.png" },
  { id: 214, name: "DJ Milk Eclairs Jar", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Milk Eclairs Jar Markup.png" },
  { id: 215, name: "DJ Milkshake Toffee", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Milkshake Toffee Markup.png" },
  { id: 216, name: "DJ Mint Cool Candy", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Mint Cool Candy Markup.png" },
  { id: 217, name: "DJ My Milk Jar", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ My Milk Markup Jar.png" },
  { id: 218, name: "DJ Plutoo Candy", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ Plutoo Candy Markup.png" },
  { id: 219, name: "DJ Tamarind Blast", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ TAMARIND BLAST MARKUP.png" },
  { id: 220, name: "DJ Tangy Tamarind", category: "Candies & Toffees", image: "/Category/Candies and toffees/DJ TANGY TAMARIND Markup.png" },
  { id: 221, name: "Tick Tick Fruity Milky", category: "Candies & Toffees", image: "/Category/Candies and toffees/TICK TICK FRUITY MILKY.png" },
  { id: 222, name: "Tick Tick Lemon", category: "Candies & Toffees", image: "/Category/Candies and toffees/TICK TICK LEMON.png" },
  { id: 223, name: "Tick Tick Lychee", category: "Candies & Toffees", image: "/Category/Candies and toffees/TICK TICK LYCHEE.png" },
  { id: 224, name: "Tick Tick Menthol", category: "Candies & Toffees", image: "/Category/Candies and toffees/TICK TICK MENTHOL.png" },
  { id: 225, name: "Tick Tick Peanut", category: "Candies & Toffees", image: "/Category/Candies and toffees/TICK TICK PEANUT.png" },
  { id: 226, name: "Tick Tick Tamarind", category: "Candies & Toffees", image: "/Category/Candies and toffees/TICK TICK TAMARIND.png" },

  // Chocolates (Category/Chocolates)
  { id: 301, name: "DJ Cocovibe", category: "Chocolates", image: "/Category/Chocolates/DJ Cocovibe Markup.png" },
  { id: 302, name: "DJ Frenzy", category: "Chocolates", image: "/Category/Chocolates/DJ Frenzy Markup.png" },
  { id: 303, name: "DJ Starvibe", category: "Chocolates", image: "/Category/Chocolates/DJ Starvibe Markup.png" },

  // Cookies & Biscuits (Category/Bicsuits and Wafers)
  { id: 401, name: "BABA MILK FRESH", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/BABA MILK FRESH Markup.png" },
  { id: 402, name: "Boost Chocolate", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/Boost Chocolate.png" },
  { id: 403, name: "DJ American Biscuits Combine", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ American Biscuits Markup Combine.png" },
  { id: 404, name: "DJ American Biscuits", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ American Biscuits Markup.png" },
  { id: 405, name: "DJ Boost wheat", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Boost wheat.png" },
  { id: 406, name: "DJ Butter Cookies", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Butter Cookies.png" },
  { id: 407, name: "DJ Cashew Cookies", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CASHEW COOKIES.png" },
  { id: 408, name: "DJ Chocochip Cookies", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CHOCOCHIP COOKIES.png" },
  { id: 409, name: "DJ Coconut Cookies", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ COCONUT COOKIES.png" },
  { id: 410, name: "DJ Cream Chocolate", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREAM CHOCOLATE MARKUP.png" },
  { id: 411, name: "DJ Cream Combine", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREAM COMBINE.png" },
  { id: 412, name: "DJ Cream Fresh", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREAM FRESH MARKUP.png" },
  { id: 413, name: "DJ Cream Mango", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREAM MANGO MARKUP.png" },
  { id: 414, name: "DJ Cream Pineapple", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREAM PINEAPPLE MARKUP.png" },
  { id: 415, name: "DJ Cream Strawberry", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREAM STRAWBERRY MARKUP.png" },
  { id: 416, name: "DJ Cream Vanilla", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREAM VANILLA MARKUP.png" },
  { id: 417, name: "DJ Cremo Chocolate", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREMO CHOCOLATE Markup.png" },
  { id: 418, name: "DJ Cremo Combine", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREMO COMBINE.png" },
  { id: 419, name: "DJ Cremo Mango", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREMO MANGO markup.png" },
  { id: 420, name: "DJ Cremo Orange", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREMO ORANGE Markup.png" },
  { id: 421, name: "DJ Cremo Pineapple", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREMO PINEAPPLE Markup.png" },
  { id: 422, name: "DJ Cremo Strawberry", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREMO STRAWBERRY MARKUP.png" },
  { id: 423, name: "DJ Cremo Vanilla", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ CREMO VANILLA Markup.png" },
  { id: 424, name: "DJ Conico Chocolate", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Conico Chocolate.png" },
  { id: 425, name: "DJ Conico Mango", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Conico Mango.png" },
  { id: 426, name: "DJ Conico Orange", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Conico Orange.png" },
  { id: 427, name: "DJ Conico Strawberry", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Conico Strawberry.png" },
  { id: 428, name: "DJ Creamy Topper Combine", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Creamy Topper Combine.png" },
  { id: 429, name: "DJ Creamy topper Chocolate", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Creamy topper Chocolate Markup.png" },
  { id: 430, name: "DJ Creamy topper Mango", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Creamy topper Mango Markup.png" },
  { id: 431, name: "DJ Creamy topper Orange", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Creamy topper Orange Markup.png" },
  { id: 432, name: "DJ Creamy topper Strawberry", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Creamy topper Strawberry Markup.png" },
  { id: 433, name: "DJ Finger Shortbread", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ FINGER SHORTBREAD COOKIES.png" },
  { id: 434, name: "DJ Football", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Football Markup.png" },
  { id: 435, name: "DJ Glucose", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Glucose Markup.png" },
  { id: 436, name: "DJ Milk Cookies", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Milk Cookies.png" },
  { id: 437, name: "DJ Milk Plus", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Milk Plus Markup.png" },
  { id: 438, name: "DJ Nice", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Nice Markup.png" },
  { id: 439, name: "DJ Original Shortbread", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ ORIGINAL SHORTBREAD.png" },
  { id: 440, name: "DJ Pistachio Cookies", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ PISTACHIO COOKIES.png" },
  { id: 441, name: "DJ Short Bread", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ SHORT BREAD COOKIES.png" },
  { id: 442, name: "DJ Superb Cookies", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ SUPERB COOKIES.jpeg" },
  { id: 443, name: "DJ Wafers Chocolate", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Wafers Chocolate.png" },
  { id: 444, name: "DJ Wafers Strawberry", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Wafers Strawberry.png" },
  { id: 445, name: "DJ Wafers Vanilla", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/DJ Wafers Vanilla.png" },
  { id: 446, name: "Maravila Chocolate", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/Maravila ChocolatevMarkup.png" },
  { id: 447, name: "Maravila Orange", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/Maravila Orange Markup.png" },
  { id: 448, name: "Maravila Strawberry", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/Maravila StrawberryMarkup.png" },
  { id: 449, name: "Maravilha Vanilla", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/Maravilha Vanilla Markup.png" },
  { id: 450, name: "Maravilha Combine", category: "Cookies & Biscuits", image: "/Category/Bicsuits and Wafers/Maravilha combine markup.png" },
];
