-- Create the products table
CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text NOT NULL,
  category text NOT NULL,
  image text NOT NULL,
  price text DEFAULT 'Export Grade'
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read the products
CREATE POLICY "Allow anonymous reads" ON public.products
  FOR SELECT USING (true);

-- Allow all operations for now (can be restricted to authenticated admin users later)
CREATE POLICY "Allow all operations for admin" ON public.products
  FOR ALL USING (true);
